### ISSUE TITLE
Why not use T and type functions instead of any-type, in definition file

### ISSUE THREAD

**Issue by Baxterboom** [morrisjdev/Linq4JS#2]
Why not use the power of generics and skip the any-cancer, like:

`  OrderBy<T>(keySelector: (key: T) => any): Array<T>;`

`  ForEach<T>(predicate: (item: T) => boolean | any): Array<T>; //if return true|any: continue, false: break;`

`  Where<T>(predicate: (item: T) => boolean): Array<T>;`

**Comment by morrisjdev** [comment]
I use `any ` because I want to give the ability to use strings as filter etc.

For example:

`array.OrderBy("x => x.name");`

And then the type isn't anonymous function with one parameter.

But the ForEach behavior for true/false return values is a good point.

Thank you.

**Comment by morrisjdev** [comment]
I just thougt about it and now I'm really happy you wrote. I will implement the Definitions almost as you suggested:

`Where(filter: ((item: T) => boolean) | string): Array<T>;`

Thank you a lot again ;)

**Comment by Baxterboom** [comment]
Awesome, with this typed definition i will seriously start looking into what you built! Let me know if i can contribute in any other way!
