### ISSUE TITLE
Modules instead of namespaces

### ISSUE THREAD

**Issue by lpcarignan** [morrisjdev/Linq4JS#4]
I'm trying to import Linq4JS in my Typescript project. 

When I try the following at the top of my file:

`import * as Linq4JS from "linq4js";`

I get the following error: 

`node_modules/linq4js/dist/linq4js.d.ts'  is not a module.`

Based on the [Namespaces and modules](https://www.typescriptlang.org/docs/handbook/namespaces-and-modules.html) documentation, I would suggest removing namespaces from your .d.ts file.

I believe another way of doing it would be to export the namespace with the following lines at the beginning of your linq4js.d.ts file:

```
export = Linq4JS;
export as namespace Linq4JS;
```

This is what I did and it fixed my error message. React has the same definition at the start so if you want to keep your namespaces, you could just do that.

But now, when I try to write Linq on my arrays, it can't find the functions. For example:

```
let stages = new Array<Stage>();
stages.Where(x => x.Name = "");
```
I get the following error message from Typescript compiler:

`TS2339: Property 'Where' does not exist on type 'Stage[]'.`

I did look at you sample code to help me out. I didn't find any examples for this situation. I tried Linq4JS in RunKit and it did work with the following example:

```
var stages = [0,1,2,3,4,5];
let results = stages.Where(x => x == 0);
console.log(results); 
```

Would it be possible to advise how I could get Linq4Js working a another Typescript project? I am running VS Code 1.13.0 with Typescript 2.3.0

**Comment by morrisjdev** [comment]
Hi lpcarignan.

You cannot import linq4js as a variable, because it only extends the prototype of array and provides some static methods. So you just need to do an import in your index.ts or something like that and the functions should available in your complete project. Just use:

```
import "linq4js";
```

Thank you for your request. I will add an Example for the import.

**Comment by lpcarignan** [comment]
Thank you for your help @morrisjdev. It does work in a sample project. Intellisence in VSCode detects linq4js and it compiles with tsc.

Would you have any idea why it won't compile with a larger project? My project has more than 50 Typescript files and a lot of dependencies. Would you have cues as to where to look for?

While building your library, did it came in conflicts with specifics of Typescript or conflicts with NodeJs? Have you heard if some global packages can conflicts with the added prototypes to the Array prototype?

**Comment by morrisjdev** [comment]
I am working with Typescript and big projects and everything is working fine. I am using gulp in combination with webpack to compile and bundle the packages. I paste parts of a gulpfile and a tsconfig of a project to give you an example.

tsconfig.json
```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "sourceMap": true,
    "target": "es5",
    "module": "commonjs",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": true,
    "lib": [
      "es2015",
      "dom"
    ]
  },
  "include": [
    "wwwroot/typescript/**/*"
  ]
}
```

important parts from gulpfile.js
```
var gulp = require("gulp");
var gutil = require("gulp-util");
var merge = require("merge2");
var webpack = require("webpack");
var webpackDevServer = require("webpack-dev-server");
var liveReload = require("webpack-livereload-plugin");
var tslint = require("gulp-tslint");
var typescript = require("gulp-typescript");
var ts = typescript.createProject("tsconfig.json");
var sourcemaps = require("gulp-sourcemaps");

var webpackConfig = function (dev) {
    return {
        entry: {
            main: "./wwwroot/build/js/index.js"
        },
        devtool: dev === true ? "inline-eval-cheap-source-map" : "source-map",
        module: {
            rules: [
                {
                    test: /\.js$/,
                    use: ["source-map-loader"],
                    enforce: "pre"
                }
            ]
        },
        output: {
            path: __dirname + "/wwwroot/bundle",
            filename: "[name].bundle.js"
        },
        plugins: [
            new liveReload(),
            new webpack.ProvidePlugin({
                $: "jquery",
                jQuery: "jquery",
                "window.jQuery": "jquery"
            })
        ],
        resolve: {
            modules: ["node_modules", "bower_components"],
            descriptionFiles: ['package.json', 'bower.json']
        }
    };
};

gulp.task("tslint", function () {
    return ts.src()
        .pipe(tslint({
            formatter: "stylish"
        }))
        .pipe(tslint.report({
            emitError: false,
            summarizeFailureOutput: true
        }));
});

gulp.task("typescript", ["tslint"], function () {
    return ts.src()
        .pipe(sourcemaps.init())
        .pipe(ts())
        .pipe(sourcemaps.write())
        .pipe(gulp.dest("wwwroot/build/js"));
});

gulp.task("watch", function () {
    new webpackDevServer(webpack(webpackConfig(true)), { quiet: true }).listen(6949, "localhost", 
    function (err) {
        if (err) throw new gutil.PluginError("webpack-dev-server", err);
        gutil.log("[webpack-dev-server]", "http://localhost:6949/main.bundle.js");
    });

    gulp.watch("wwwroot/typescript/**/*", ["typescript"]);
});
```

Conflicts with other packages can occur, but because the method names are oriented at C#'s PascalCase Naming I think conflicts are not very likely.

Hope this helps you.
