### ISSUE TITLE
Consider using Object.defineProperty when extending Array 

### ISSUE THREAD

**Issue by Baxterboom** [morrisjdev/Linq4JS#5]
Have you considered using Object.defineProperty(Array.prototype, "XXXX", {enumerable:false}); when you extend Array? 
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty

If someone enumerate with for(var key in data) {...} you will iterate over your properties also, not just the array items that is default. This is bad IMO. 

To simplify things Typescript has a concept of decorator(s)
http://www.sparkbit.pl/typescript-decorators/
http://resolvethis.com/creating-typescript-non-enumerable-property-decorator/

I would help you but cant install the node packages
`
npm ERR! enoent ENOENT: no such file or directory, rename 'Z:\Development\Temp\Linq4JS\node_modules\<some-package>' -> 'Z:\Development\Temp\Linq4JS\node_modules\.<some-package>.DELETE'
`

**Comment by Baxterboom** [comment]
Have a look at https://github.com/Baxterboom/Linq4JS/commit/43ed33a2c47a4959cf91b363afe41f195dee4810

Couldn't get decorators to work when on Array.prototype so i wrapped it (NonEnumerable). Can probably be improved. This hides the properties from enumeration.

_default behavior_
```
for (var i in [1, 2]) console.log(i); // result = 1, 2
```

_current behavior_
```
Array.prototype.Add = function () { };
for (var i in [1, 2]) console.log(i); // result = 1, 2, Add
```

_desired behavior (my commit)_
```
Object.defineProperty(Array.prototype, "Add", {
	value: function () { },
	enumerable: false
});
for (var i in [1, 2]) console.log(i); // result = 1, 2
```

**Comment by Baxterboom** [comment]
Another thing i worried about is object pollution, it should be kept at a minimum. Like these properties:
```
//IArray.ts
Order: Linq4JS.OrderEntry[];
GroupValue: any;
```
how about put them in a (one) _linq4JS property on the array (instead as direct properties) and as non enumerable? Minimum pollution, and you have ONE object you can put your logic into. This object can also hold global customization settings like defaultIdSelector for you GeneratedEntity.

The GeneratedEntity, it also "pollute" objects. Use same pattern, _linq4JS property? Can you describe the purpose of this. I noticed its used in Add, Remove, Update, simplify usage or project specific?

**Comment by morrisjdev** [comment]
Thank you. Looks great. I will review if I have time ;)
