### ISSUE TITLE
"let" and "let that: T[] = this;"

### ISSUE THREAD

**Issue by Baxterboom** [morrisjdev/Linq4JS#6]
I see your going for "let" when "const" would be more accurate. 

Also 
```
let that: T[] = this;
```
is unnecessary and removing it from js saves ~1k 
FYI: good explanation of "this closure" https://github.com/Microsoft/TypeScript/wiki/%27this%27-in-TypeScript

**Comment by Baxterboom** [comment]
I have done considerable changes regarding this, and some code cleanup in my fork https://github.com/Baxterboom/Linq4JS if you are interested.

**Comment by morrisjdev** [comment]
Thats a really great hint. Thank you. If I have time I will review all things you made.

Thanks a lot ;)
